/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.casohistoriales;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.mycompany.pasteleriagenerarreporte.FuncionalidadGenerarReporte;
import com.mycompany.pasteleriagenerarreporte.IFuncionalidadGenerarReporte;
import com.mycompany.pasteleriaguardarreportes.FuncionalidadGuardarReportes;
import com.mycompany.pasteleriaguardarreportes.IFuncionalidadGuardarReportes;
import com.mycompany.pasteleriaproductosventa.FuncionalidadConsultarProductos;
import control.ControlHistoriales;
import dto.DTO_Cliente;
import dto.DTO_DetalleVenta;
import dto.DTO_Producto;
import dto.DTO_Venta;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import com.mycompany.pasteleriaproductosventa.IFuncionalidadConsultarProductos;
import dto.DTO_DetallesVentaReporte;
import dto.DTO_GenerarReporte;
import dto.DTO_ReciboFormato;
import dto.DTO_Reporte;
import java.awt.Desktop;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author abelc
 */
public class Presentacion_FrmDetallesVenta extends javax.swing.JFrame {

    private ControlHistoriales control;
    private DTO_Cliente cliente;
    private DTO_Venta venta;
    private IFuncionalidadConsultarProductos funcionalidadConsultarProducto;
    private IFuncionalidadGenerarReporte generarReporte;
private IFuncionalidadGuardarReportes guardarRecibo;
    /**
     * Creates new form FrmDetallesVenta
     */
    public Presentacion_FrmDetallesVenta() {
        this.control = ControlHistoriales.getInstance();
        this.cliente = new DTO_Cliente();
        this.venta = control.getVenta();
        this.guardarRecibo=new FuncionalidadGuardarReportes();
        funcionalidadConsultarProducto = new FuncionalidadConsultarProductos();
        generarReporte = new FuncionalidadGenerarReporte();
        setTitle("Detalles de la venta");
        initComponents();
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        detallesVentaLabel.setText("Fecha de compra: " + ff.format(venta.getFechaRegistro()));
        fechaEntregalabel.setText("Fecha de entrega: " + ff.format(venta.getFechaEntrega()));
        totalVentalabel.setText("Total: " + Float.toString(venta.getMontoTotal()));
        estadoLabel.setText("Historial: " + venta.getEstado());
        clienteLabel.setText("Cliente: " + venta.getCliente().getNombre() + " " + venta.getCliente().getApellidoP() + " " + venta.getCliente().getApellidoM());
        numTelefonoLbl.setText("Numero de telefono: " + venta.getCliente().getTelefono());
        String calle = venta.getDireccionEntrega().getCalle();
        if ("En tienda".equals(calle)) {
            calleLbl.setText("En tienda");
            if (calle == null) {
                calleLbl.setText("");
            }
        } else {
            calleLbl.setText("calle: " + calle);
        }
        String colonia = venta.getDireccionEntrega().getColonia();
        if (colonia != null) {
            coloniaLbl.setText("Colonia: " + colonia);
        } else {
            coloniaLbl.setText(" ");
        }
        String numExterior = venta.getDireccionEntrega().getNumExterior();
        if (numExterior != null) {
            jLabel8.setText("Num Exterior: #" + numExterior);
        } else {
            jLabel8.setText("");
        }
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detallesVentaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        fechaEntregalabel = new javax.swing.JLabel();
        totalVentalabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallesVentaTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        generarReciboBtn = new javax.swing.JButton();
        clienteLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numTelefonoLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calleLbl = new javax.swing.JLabel();
        coloniaLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Detalles de la venta");

        detallesVentaLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        detallesVentaLabel.setForeground(new java.awt.Color(0, 0, 0));
        detallesVentaLabel.setText("Fecha de la compra:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Detalles de la venta");

        estadoLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadoLabel.setText("Estado:");

        fechaEntregalabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fechaEntregalabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaEntregalabel.setText("Fecha de entrega:");

        totalVentalabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        totalVentalabel.setForeground(new java.awt.Color(0, 0, 0));
        totalVentalabel.setText("Total:");

        detallesVentaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Especificaciones", "Cantidad", "Costo", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detallesVentaTabla.setRowSelectionAllowed(false);
        detallesVentaTabla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        detallesVentaTabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        detallesVentaTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        detallesVentaTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        detallesVentaTabla.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(detallesVentaTabla);

        jButton1.setBackground(new java.awt.Color(140, 220, 254));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        generarReciboBtn.setBackground(new java.awt.Color(140, 220, 254));
        generarReciboBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        generarReciboBtn.setForeground(new java.awt.Color(0, 0, 0));
        generarReciboBtn.setText("Generar recibo");
        generarReciboBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReciboBtnActionPerformed(evt);
            }
        });

        clienteLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clienteLabel.setForeground(new java.awt.Color(0, 0, 0));
        clienteLabel.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Datos de la venta");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Datos del cliente");

        numTelefonoLbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        numTelefonoLbl.setForeground(new java.awt.Color(0, 0, 0));
        numTelefonoLbl.setText("Numero de telefono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Datos de entrega");

        calleLbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        calleLbl.setForeground(new java.awt.Color(0, 0, 0));
        calleLbl.setText("Calle: ");

        coloniaLbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        coloniaLbl.setForeground(new java.awt.Color(0, 0, 0));
        coloniaLbl.setText("Colonia: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Num exterior: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generarReciboBtn)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(186, 186, 186))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(numTelefonoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaEntregalabel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(detallesVentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(totalVentalabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coloniaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaEntregalabel)
                    .addComponent(detallesVentaLabel)
                    .addComponent(clienteLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(totalVentalabel)
                    .addComponent(numTelefonoLbl))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calleLbl)
                    .addComponent(coloniaLbl)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarReciboBtn)
                    .addComponent(jButton1))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        control.mostrarHistorialVentas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generarReciboBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReciboBtnActionPerformed

        try {
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            DTO_ReciboFormato recibo = new DTO_ReciboFormato();
            recibo.setNombre(venta.getCliente().getNombre() + " " + venta.getCliente().getApellidoP() + " " + venta.getCliente().getApellidoM());
            recibo.setFechaCompra(ff.format(venta.getFechaRegistro()));
            recibo.setTotal("$" + Float.toString(venta.getMontoTotal()));
            List<DTO_DetallesVentaReporte> detallesVenta = new ArrayList<>();
            for (DTO_DetalleVenta ventaDetalle : venta.getDetallesVenta()) {
                DTO_DetallesVentaReporte dv = new DTO_DetallesVentaReporte();
                dv.setCantidad(Integer.toString(ventaDetalle.getCantidad()));
                dv.setImporte(Float.toString(ventaDetalle.getImporte()));
                dv.setProducto(ventaDetalle.getProducto().getNombre());
                dv.setPrecio(Float.toString(ventaDetalle.getPrecio()));
                detallesVenta.add(dv);
            }
            recibo.setDetallesVenta(detallesVenta);
            DTO_GenerarReporte reporteGenerado = generarReporte.generarRecibo(recibo);

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporteGenerado.getJasperReport(), reporteGenerado.getParameters(), new JREmptyDataSource());

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar como...");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
            fileChooser.setFileFilter(filter);
            int seleccion = fileChooser.showSaveDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();
                String rutaArchivo = archivoSeleccionado.getAbsolutePath();

                if (!rutaArchivo.toLowerCase().endsWith(".pdf")) {
                    rutaArchivo += ".pdf";
                }

                JasperExportManager.exportReportToPdfFile(jasperPrint, rutaArchivo);
                JOptionPane.showMessageDialog(this, "El archivo se ha guardado correctamente en:\n" + rutaArchivo, "Archivo guardado", JOptionPane.INFORMATION_MESSAGE);

                if (Desktop.isDesktopSupported()) {
                    File archivo = new File(rutaArchivo);
                    DTO_Reporte reporte = new DTO_Reporte();
                    byte[] bytesArchivo = convertirArchivoABytes(archivo);
                    reporte.setBytesContenido(bytesArchivo);
                    reporte.setNombre(archivo.getName());
                    reporte.setCategoria("Recibo");
                    reporte.setTipo("application/pdf");
                    reporte.setFechaExpedicion(new Date());
                    guardarRecibo.guardarReporte(reporte);
                    Desktop.getDesktop().open(new File(rutaArchivo));

                }

            }
        } catch (JRException ex) {
            Logger.getLogger(Presentacion_FrmDetallesVenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Presentacion_FrmDetallesVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_generarReciboBtnActionPerformed

    public void mostrarDetallesVentas() {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("extras");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion_FrmDetallesVenta().setVisible(true);
            }
        });
    }

    private void llenarTabla() {
        limpiarTabla();
        List<DTO_DetalleVenta> detallesVenta = venta.getDetallesVenta();
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();
        detallesVenta.forEach(t -> {
            modelo.addRow(new Object[]{t.getProducto().getNombre(), t.getEspecificacion(),
                t.getCantidad(), t.getPrecio(), t.getImporte()
            });
        });
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();

        modelo.setRowCount(0);

        detallesVentaTabla.setModel(modelo);
    }

    private byte[] convertirArchivoABytes(File archivo) {
        try (FileInputStream fis = new FileInputStream(archivo); ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[1024];
            int longitud;
            while ((longitud = fis.read(buffer)) != -1) {
                bos.write(buffer, 0, longitud);
            }
            return bos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calleLbl;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel coloniaLbl;
    private javax.swing.JLabel detallesVentaLabel;
    private javax.swing.JTable detallesVentaTabla;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel fechaEntregalabel;
    private javax.swing.JButton generarReciboBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numTelefonoLbl;
    private javax.swing.JLabel totalVentalabel;
    // End of variables declaration//GEN-END:variables
}
