/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.casohistoriales;

import com.mycompany.pasteleriaconsultarreportes.FuncionalidadConsultarReportes;
import com.mycompany.pasteleriaconsultarreportes.IFuncionalidadConsultarReportes;
import com.mycompany.pasteleriaeliminarreporte.FuncionalidadEliminarReporte;
import com.mycompany.pasteleriaeliminarreporte.IFuncionalidadEliminarReporte;
import com.mycompany.pasteleriaguardarreportes.FuncionalidadGuardarReportes;
import com.mycompany.pasteleriaguardarreportes.IFuncionalidadGuardarReportes;
import dto.DTO_Reporte;

import extras.TableActionCellEditor;
import extras.TableActionCellRender;
import extras.TableActionEvent;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abelc
 */
public class Presentacion_FrmHistorialReportes extends javax.swing.JFrame {

    private IFuncionalidadConsultarReportes funcionalidadReportes;
    private List<DTO_Reporte> listaReporte;
    private IFuncionalidadEliminarReporte funcionalidadEliminar;
    private SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
    

    /**
     * Creates new form Presentacion_DlgHistorialeReportes
     */
    public Presentacion_FrmHistorialReportes() {
        funcionalidadReportes = new FuncionalidadConsultarReportes();
        funcionalidadEliminar = new FuncionalidadEliminarReporte();
         
        setTitle("Historial de registros");
        initComponents();

        listaReporte = funcionalidadReportes.consultarReportes(listaReporte);
        llenarTabla();
        TableActionEvent event = new TableActionEvent() {

            @Override
            public void onDelete(int row) {
                if (tablaReportes.isEditing()) {
                    tablaReportes.getCellEditor().stopCellEditing();
                }
                System.out.println(listaReporte.get(row).getId());
                funcionalidadEliminar.eliminarReporte(listaReporte.get(row));
                DefaultTableModel model = (DefaultTableModel) tablaReportes.getModel();

                model.removeRow(row);
            }

            @Override
            public void onView(int row) {
                VerPdf verPdf = new VerPdf(listaReporte.get(row).getBytesContenido());
            }
        };
        tablaReportes.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        tablaReportes.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
        tablaReportes.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
                setHorizontalAlignment(SwingConstants.RIGHT);
                return super.getTableCellRendererComponent(jtable, o, bln, bln1, i, i1);
            }
        });
    }

    private void llenarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tablaReportes.getModel();
        if (listaReporte != null) {
            listaReporte.forEach(t -> {
                modelo.addRow(new Object[]{t.getNombre(), t.getCategoria(), ff.format(t.getFechaExpedicion()), ""});
            });
        }

    }

    
    public void mostrarHistorialReportes(){
    java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Presentacion_FrmHistorialReportes().setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Historial de reportes");

        jButton1.setBackground(new java.awt.Color(140, 220, 254));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Fecha de expedición", ""
            }
        ));
        tablaReportes.setRowHeight(40);
        jScrollPane1.setViewportView(tablaReportes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 414, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
}
