/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.mycompany.pasteleriaproductosventa.FuncionalidadProductos;
import com.mycompany.pasteleriaproductosventa.IFuncionalidadProductos;
import control.ControlHistoriales;
import dto.DTO_Cliente;
import dto.DTO_DetalleVenta;
import dto.DTO_Producto;
import dto.DTO_Venta;
import java.awt.Font;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abelc
 */
public class Presentacion_FrmDetallesVenta extends javax.swing.JFrame {

    private ControlHistoriales control;
    private DTO_Cliente cliente;
    private DTO_Venta venta;
    private IFuncionalidadProductos funcionalidadConsultarProducto;

    /**
     * Creates new form FrmDetallesVenta
     */
    public Presentacion_FrmDetallesVenta() {
        this.control = ControlHistoriales.getInstance();
        this.cliente = new DTO_Cliente();
        this.venta = control.getVenta();
        funcionalidadConsultarProducto = new FuncionalidadProductos();
        initComponents();
        System.out.println(venta.getID());
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detallesVentaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        fechaEntregalabel = new javax.swing.JLabel();
        totalVentalabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallesVentaTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Detalles de la venta");

        detallesVentaLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        detallesVentaLabel.setForeground(new java.awt.Color(0, 0, 0));
        detallesVentaLabel.setText("Fecha de la compra:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Detalles");

        estadoLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadoLabel.setText("Estado:");

        fechaEntregalabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fechaEntregalabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaEntregalabel.setText("Fecha de entrega:");

        totalVentalabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        totalVentalabel.setForeground(new java.awt.Color(0, 0, 0));
        totalVentalabel.setText("Total de la venta:");

        detallesVentaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Especificaciones", "Cantidad", "Costo", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detallesVentaTabla.setRowSelectionAllowed(false);
        detallesVentaTabla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        detallesVentaTabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        detallesVentaTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        detallesVentaTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        detallesVentaTabla.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(detallesVentaTabla);

        jButton1.setBackground(new java.awt.Color(140, 220, 254));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");

        jButton2.setBackground(new java.awt.Color(140, 220, 254));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Generar Ticket");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cliente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detallesVentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaEntregalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(260, 260, 260)
                        .addComponent(jButton2)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(totalVentalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallesVentaLabel)
                    .addComponent(fechaEntregalabel))
                .addGap(27, 27, 27)
                .addComponent(estadoLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(totalVentalabel)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  public void mostrarDetallesVentas() {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("extras");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion_FrmDetallesVenta().setVisible(true);
            }
        });
    }

    private void llenarTabla() {
        limpiarTabla();
        List<DTO_DetalleVenta> detallesVenta = venta.getDetallesVenta();
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();
        detallesVenta.forEach(t -> {
            DTO_Producto producto = funcionalidadConsultarProducto.consultarProductoId(t.getIdproducto());
            modelo.addRow(new Object[]{producto.getNombre(), t.getEspecificacion(),
                t.getCantidad(), t.getPrecio(), t.getImporte()
            });
        });
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();

        modelo.setRowCount(0);

        detallesVentaTabla.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detallesVentaLabel;
    private javax.swing.JTable detallesVentaTabla;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel fechaEntregalabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalVentalabel;
    // End of variables declaration//GEN-END:variables
}
