/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.mycompany.pasteleriaagregarproducto.FuncionalidadAgregarProducto;
import com.mycompany.pasteleriaagregarproducto.IFuncionalidadAgregarProducto;
import com.mycompany.pasteleriaconsultaringrediente.FuncionalidadConsultarIngrediente;
import com.mycompany.pasteleriaconsultaringrediente.IFuncionalidadConsultarIngrediente;
import control.ControlGestionarInventario;
import dto.DTO_Ingrediente;
import dto.DTO_IngredienteDetalle;
import dto.DTO_Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author af_da
 */
public class Presentacion_DlgIngredientesSeleccionados extends javax.swing.JFrame {

    private IFuncionalidadConsultarIngrediente funcionalidadConsultarIngrediente;
    private IFuncionalidadAgregarProducto funcionalidadAgregarProducto;
    private ControlGestionarInventario control;

    /**
     * Creates new form Presentacion_DlgIngredientesSeleccionados
     */
    public Presentacion_DlgIngredientesSeleccionados() {
        initComponents();
        funcionalidadConsultarIngrediente = new FuncionalidadConsultarIngrediente();
        funcionalidadAgregarProducto = new FuncionalidadAgregarProducto();
        control = ControlGestionarInventario.getInstance();
        llenarTabla();
        agregarListenerCambioCantidad();

    }

    private void llenarTabla() {
        limpiarTabla();
        List<DTO_Ingrediente> listaIngredientes = new ArrayList<>();
        List<DTO_IngredienteDetalle> ingredientesDetalleDTO = control.getProductoDTO().getIngredientes();
        System.out.println(ingredientesDetalleDTO.get(0).getNombre());

        System.out.println(ingredientesDetalleDTO.get(1).getNombre());
        if (ingredientesDetalleDTO != null) {
            for (DTO_IngredienteDetalle ingredienteDetalle : ingredientesDetalleDTO) {
                DTO_Ingrediente ingredientes = funcionalidadConsultarIngrediente.consultarIngredientePorNombre(new DTO_Ingrediente(ingredienteDetalle.getNombre()));
                listaIngredientes.add(ingredientes);
            }
        }
        DefaultTableModel modelo = (DefaultTableModel) tableIngredientes.getModel();

        if (listaIngredientes != null) {
            listaIngredientes.forEach(t -> modelo.addRow(new Object[]{t.getNombre(), null, t.getUnidadDeMedida()}));
        }

    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tableIngredientes.getModel();

        modelo.setRowCount(0);

        tableIngredientes.setModel(modelo);
    }

    private List<DTO_IngredienteDetalle> obtenerListaIngredientes() {
        JTable tabla = tableIngredientes;
        List<DTO_IngredienteDetalle> listaIngredientes = control.getProductoDTO().getIngredientes();
        int numRows = tabla.getRowCount();

        for (int fila = 0; fila < numRows; fila++) {
            Object valorCelda = tabla.getValueAt(fila, 1);
            DTO_IngredienteDetalle ingrediente = listaIngredientes.get(fila);
            ingrediente.setCantidad(Integer.valueOf(String.valueOf(valorCelda)));
        }

        return listaIngredientes;
    }

    public void agregarListenerCambioCantidad() {
        final int columnaNumero = 1;

        tableIngredientes.getColumnModel().getColumn(columnaNumero).setCellEditor(new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean stopCellEditing() {
                try {
                    JTextField textField = (JTextField) getComponent();
                    String valorCelda = textField.getText();
                    double numero = Double.parseDouble(valorCelda);

                    if (numero < 0) {
                        JOptionPane.showMessageDialog(null, "El número debe ser igual o menor que 0", "Error", JOptionPane.ERROR_MESSAGE);
                        return false; // Permite al usuario corregir el valor
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }

                return super.stopCellEditing();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableIngredientes = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIngredientes.setRowHeight(25);
        jScrollPane1.setViewportView(tableIngredientes);
        if (tableIngredientes.getColumnModel().getColumnCount() > 0) {
            tableIngredientes.getColumnModel().getColumn(0).setResizable(false);
            tableIngredientes.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAceptar.setBackground(new java.awt.Color(140, 220, 254));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese las cantidades de cada ingrediente.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAceptar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        control.getProductoDTO().setIngredientes(obtenerListaIngredientes());
        DTO_Producto producto = control.getProductoDTO();
        funcionalidadAgregarProducto.agregarProducto(producto);
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableIngredientes;
    // End of variables declaration//GEN-END:variables
}
