/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.facturar;

import com.mycompany.pasteleriaconsultarreportes.FuncionalidadConsultarReportes;
import com.mycompany.pasteleriaconsultarreportes.IFuncionalidadConsultarReportes;
import com.mycompany.pasteleriaeliminarreporte.FuncionalidadEliminarReporte;
import com.mycompany.pasteleriaeliminarreporte.IFuncionalidadEliminarReporte;
import com.mycompany.pasteleriagenerarreporte.FuncionalidadGenerarReporte;
import com.mycompany.pasteleriagenerarreporte.IFuncionalidadGenerarReporte;
import control.ControlFacturar;
import dto.DTO_DetalleVenta;
import dto.DTO_DetallesVentaReporte;
import dto.DTO_Factura;
import dto.DTO_FacturaFormato;
import extras.ButtonColumn;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class Presentacion_FrmHistorialFacturas extends javax.swing.JFrame {

    private ControlFacturar controlFacturar;
    private IFuncionalidadConsultarReportes funcionalidadReportes;
    private IFuncionalidadGenerarReporte funcionalidadGenerarReporte;
    private List<DTO_Factura> listaFacturas;
    private IFuncionalidadEliminarReporte funcionalidadEliminar;
    private SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form Presentacion_FrmHistorialFacturas
     */
    public Presentacion_FrmHistorialFacturas() {
        initComponents();
        controlFacturar = ControlFacturar.getInstance();
        llenarTabla();

        funcionalidadReportes = new FuncionalidadConsultarReportes();
        funcionalidadGenerarReporte = new FuncionalidadGenerarReporte();
        funcionalidadEliminar = new FuncionalidadEliminarReporte();

        setTitle("Historial de registros");
        initComponents();

        listaFacturas = funcionalidadReportes.consultarFacturas(listaFacturas);
        llenarTabla();
    }

    private void llenarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tableFacturas.getModel();
        if (listaFacturas != null) {
            listaFacturas.forEach(t -> {
                modelo.addRow(new Object[]{t.getId(), ff.format(t.getFechaEmision()), ff.format(t.getFechaVencimiento()), t.getVentaId()});
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDescargar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(18, 149, 205));

        btnVolver.setText("Volver");
        btnVolver.setBackground(new java.awt.Color(18, 111, 161));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel6.setText("FACTURAR");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(149, 149, 149)
                .addComponent(btnVolver)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btnVolver))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "EMSIÓN", "VENCIMEINTO", "ID VENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableFacturas);

        jLabel1.setText("Historial de facturas:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnDescargar.setText("Eliminar");
        btnDescargar.setBackground(new java.awt.Color(18, 111, 161));
        btnDescargar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDescargar.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(18, 111, 161));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Descargar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(88, 88, 88)
                        .addComponent(btnDescargar)
                        .addGap(175, 175, 175))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescargar)
                    .addComponent(btnEliminar))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlFacturar.mostrarDlgOpcionFactura();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        ButtonColumn desplegarButtonColumn = new ButtonColumn("Desplegar Ventas", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int filaSeleccionada = tableFacturas.getSelectedRow();
                if (filaSeleccionada != -1) {
                    controlFacturar.setFactura((DTO_Factura) tableFacturas.getValueAt(filaSeleccionada, 0));
                    try {
                        DTO_FacturaFormato facturaFormato = new DTO_FacturaFormato();
                        List<DTO_DetallesVentaReporte> detallesVenta = new ArrayList<>();
                        for (DTO_DetalleVenta ventaDetalle : controlFacturar.getVenta().getDetallesVenta()) {
                            DTO_DetallesVentaReporte dv = new DTO_DetallesVentaReporte();
                            dv.setCantidad(Integer.toString(ventaDetalle.getCantidad()));
                            dv.setImporte(Float.toString(ventaDetalle.getImporte()));
                            dv.setProducto(ventaDetalle.getProducto().getNombre());
                            dv.setPrecio(Float.toString(ventaDetalle.getPrecio()));
                            detallesVenta.add(dv);
                        }
                        facturaFormato.setDetallesVenta(detallesVenta);
                        facturaFormato.setRfcCliente(controlFacturar.getCliente().getRfc());
                        facturaFormato.setNombreCliente(controlFacturar.getCliente().getNombre());
                        facturaFormato.setDireccionCliente(controlFacturar.getCliente().getDirecciones().get(0).toString());
                        String total = "$" + controlFacturar.getVenta().getMontoTotal();
                        facturaFormato.setTotal(total);
                        funcionalidadGenerarReporte.generarReporteFactura(facturaFormato);
                        controlFacturar.setFactura(null);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
    }//GEN-LAST:event_btnDescargarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ButtonColumn desplegarButtonColumn = new ButtonColumn("Desplegar Ventas", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int filaSeleccionada = tableFacturas.getSelectedRow();
                if (filaSeleccionada != -1) {
                    controlFacturar.setFactura((DTO_Factura) tableFacturas.getValueAt(filaSeleccionada, 0));
                    try {
                        funcionalidadEliminar.eliminarFactura(controlFacturar.getFactura());
                        controlFacturar.setFactura(null);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFacturas;
    // End of variables declaration//GEN-END:variables
}
