/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.facturar;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.mycompany.pasteleriaconsultarreportes.FuncionalidadConsultarReportes;
import com.mycompany.pasteleriaconsultarreportes.IFuncionalidadConsultarReportes;
import com.mycompany.pasteleriagenerarreporte.FuncionalidadGenerarReporte;
import com.mycompany.pasteleriagenerarreporte.IFuncionalidadGenerarReporte;
import com.mycompany.pasteleriaguardarreportes.FuncionalidadGuardarReportes;
import com.mycompany.pasteleriaguardarreportes.IFuncionalidadGuardarReportes;
import consultarClientes.IFuncionalidadConsultarClientes;
import control.ControlFacturar;
import dto.DTO_DetalleVenta;
import dto.DTO_DetallesVentaReporte;
import dto.DTO_Factura;
import dto.DTO_FacturaFormato;
import dto.DTO_GenerarReporte;
import dto.DTO_Reporte;
import java.awt.Desktop;
import java.awt.Font;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import presentacion.Presentacion_MenuPrincipal;
import presentacion.casohistoriales.Presentacion_FrmDetallesVenta;

/**
 *
 * @author PERSONAL
 */
public class Presentacion_FrmConfirmarGenerarFactura extends javax.swing.JFrame {

    IFuncionalidadGenerarReporte generar;
    IFuncionalidadGuardarReportes guardar;
    IFuncionalidadConsultarReportes consultar;
    ControlFacturar control;

    /**
     * Creates new form Presentacion_FrmConfirmarGenerarFactura
     */
    public Presentacion_FrmConfirmarGenerarFactura() {
        initComponents();
        control = ControlFacturar.getInstance();
        generar = new FuncionalidadGenerarReporte();
        guardar = new FuncionalidadGuardarReportes();
        consultar = new FuncionalidadConsultarReportes();
        lblNombre.setText(control.getCliente().getNombre());
        lblAPaterno.setText(control.getCliente().getApellidoP());
        lblAMaterno.setText(control.getCliente().getApellidoM());
        lblDireccion.setText(control.getDireccion().getCalle());
        lblRfc.setText(control.getCliente().getRfc());
        lblNombre.setText(control.getCliente().getNombre());
        lblTotalVenta.setText(control.getVenta().getMontoTotal() + "");
        lblIdVenta.setText(control.getVenta().getID());
        SimpleDateFormat ff = new SimpleDateFormat("dd/mm/yyyy");
        lblFechaVenta.setText(ff.format(control.getVenta().getFechaRegistro()));
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallesVentaTabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAPaterno = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblAMaterno = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        lblIdVenta = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotalVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(18, 149, 205));

        btnVolver.setBackground(new java.awt.Color(18, 111, 161));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FACTURAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(219, 219, 219)
                .addComponent(btnVolver)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detallesVentaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Especificaciones", "Cantidad", "Costo", "Impote"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(detallesVentaTabla);
        if (detallesVentaTabla.getColumnModel().getColumnCount() > 0) {
            detallesVentaTabla.getColumnModel().getColumn(0).setResizable(false);
            detallesVentaTabla.getColumnModel().getColumn(1).setResizable(false);
            detallesVentaTabla.getColumnModel().getColumn(2).setResizable(false);
            detallesVentaTabla.getColumnModel().getColumn(3).setResizable(false);
            detallesVentaTabla.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Datos:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre(s):");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("N/a");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Confirmar datos y generar factura:");

        btnGenerarFactura.setBackground(new java.awt.Color(18, 111, 161));
        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFactura.setText("Generar");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(18, 111, 161));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("A. Paterno:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("A. Materno:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ID Venta:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("RFC:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Fecha venta:");

        lblAPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAPaterno.setText("N/a");

        lblRfc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRfc.setText("N/a");

        lblAMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAMaterno.setText("N/a");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setText("N/a");

        lblFechaVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaVenta.setText("N/a");

        lblIdVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdVenta.setText("N/a");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Total:");

        lblTotalVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalVenta.setText("N/a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(73, 73, 73)
                        .addComponent(lblTotalVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRfc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDireccion)
                                        .addComponent(lblIdVenta)
                                        .addComponent(lblFechaVenta))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnGenerarFactura)
                                .addGap(102, 102, 102)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAPaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAMaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRfc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaVenta)))
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalVenta)
                            .addComponent(jLabel12))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarFactura)
                            .addComponent(btnCancelar))
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        System.out.println(control.getVenta().getDetallesVenta());
        control.mostrarDlgOpcionFactura();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
//        try {
//            DTO_FacturaFormato facturaFormato = new DTO_FacturaFormato();
//            List<DTO_DetallesVentaReporte> detallesVenta = new ArrayList<>();
//            for (DTO_DetalleVenta ventaDetalle : control.getVenta().getDetallesVenta()) {
//                DTO_DetallesVentaReporte dv = new DTO_DetallesVentaReporte();
//                dv.setCantidad(Integer.toString(ventaDetalle.getCantidad()));
//                dv.setImporte(Float.toString(ventaDetalle.getImporte()));
//                dv.setProducto(ventaDetalle.getProducto().getNombre());
//                dv.setPrecio(Float.toString(ventaDetalle.getPrecio()));
//                detallesVenta.add(dv);
//            }
//            facturaFormato.setDetallesVenta(detallesVenta);
//            facturaFormato.setRfcCliente(control.getCliente().getRfc());
//            facturaFormato.setNombreCliente(control.getCliente().getNombre());
//            facturaFormato.setDireccionCliente(control.getCliente().getDirecciones().get(0).toString());
//            String total = "$" + control.getVenta().getMontoTotal();
//            facturaFormato.setTotal(total);
//            facturaFormato.setIva("$" + (control.getVenta().getMontoTotal() * 0.6));
//            facturaFormato.setIva("$" + (control.getVenta().getMontoTotal() - (control.getVenta().getMontoTotal() * 0.6)));
//
//            DTO_GenerarReporte reporteGenerado = generar.generarReporteFactura(facturaFormato);
//            JasperPrint jasperPrint = JasperFillManager.fillReport(reporteGenerado.getJasperReport(), reporteGenerado.getParameters(), new JREmptyDataSource());
//
//            JFileChooser fileChooser = new JFileChooser();
//            fileChooser.setDialogTitle("Guardar como...");
//            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
//            fileChooser.setFileFilter(filter);
//            int seleccion = fileChooser.showSaveDialog(this);
//
//            if (seleccion == JFileChooser.APPROVE_OPTION) {
//                File archivoSeleccionado = fileChooser.getSelectedFile();
//                String rutaArchivo = archivoSeleccionado.getAbsolutePath();
//
//                if (!rutaArchivo.toLowerCase().endsWith(".pdf")) {
//                    rutaArchivo += ".pdf";
//                }
//
//                JasperExportManager.exportReportToPdfFile(jasperPrint, rutaArchivo);
//                JOptionPane.showMessageDialog(this, "El archivo se ha guardado correctamente en:\n" + rutaArchivo, "Archivo guardado", JOptionPane.INFORMATION_MESSAGE);
//
//                if (Desktop.isDesktopSupported()) {
//                    File archivo = new File(rutaArchivo);
//                    DTO_Factura factura = new DTO_Factura();
//                    byte[] bytesArchivo = convertirArchivoABytes(archivo); // Asegúrate de tener este método definido
//                    factura.setBytesContenido(bytesArchivo);
//                    factura.setFechaEmision(new Date());
//                    Calendar vencimiento = Calendar.getInstance();
//                    vencimiento.add(Calendar.DAY_OF_YEAR, 30);
//                    SimpleDateFormat ff = new SimpleDateFormat("dd/mm/yyyy");
//                    factura.setFechaVencimiento(vencimiento.getTime());
//                    factura.setVenta(control.getVenta());
//                    guardar.guardarFactura(factura);
//                    Desktop.getDesktop().open(new File(rutaArchivo));
//                }
//            }
//
//            guardar.guardarFactura(control.getFactura());
//            control.limpiarValores();
//            JOptionPane.showMessageDialog(null, "Factura guardada y generada con éxito");
//        } catch (Exception ex) {
//            ex.printStackTrace();
//            JOptionPane.showMessageDialog(null, ex);
//        }
//        this.dispose();
//        control.mostrarDlgOpcionFactura();

        Calendar vencimiento = Calendar.getInstance();
        vencimiento.add(Calendar.DAY_OF_YEAR, 30);
        DTO_Factura factura = new DTO_Factura(new Date(), vencimiento.getTime(), control.getVenta());
        String string = "example";
        byte[] byteArray = string.getBytes();
        factura.setBytesContenido(byteArray);
        System.out.print(guardar.guardarFactura(factura));
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private byte[] convertirArchivoABytes(File archivo) {
        try (FileInputStream fis = new FileInputStream(archivo); ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[1024];
            int longitud;
            while ((longitud = fis.read(buffer)) != -1) {
                bos.write(buffer, 0, longitud);
            }
            return bos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    private void llenarTabla() {
        limpiarTabla();
        List<DTO_DetalleVenta> detallesVenta = control.getVenta().getDetallesVenta();
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();
        detallesVenta.forEach(t -> {
            modelo.addRow(new Object[]{t.getProducto().getNombre(), t.getEspecificacion(),
                t.getCantidad(), t.getPrecio(), t.getImporte()
            });
        });
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) detallesVentaTabla.getModel();

        modelo.setRowCount(0);

        detallesVentaTabla.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTable detallesVentaTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAMaterno;
    private javax.swing.JLabel lblAPaterno;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblIdVenta;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTotalVenta;
    // End of variables declaration//GEN-END:variables
}
